### ISSUE TITLE
Styling register page

### ISSUE THREAD

**Issue by MartijnKeesmaat** [MartijnKeesmaat/Dating-app-pt#24]
Style the register page. The radio inputs are a bit confusing because they are below each other. It would be better to place them next to each other. Look into how you can style the select inputs. Use the same design of the other inputs (the grey border with no background).

Don't forget to create a new branch with
- git branch fix/register-styling
- git checkout fix/register-styling

[Link](https://www.dropbox.com/s/u9rh73wk588p1gc/Schermafdruk%202019-04-10%2013.19.48.png?dl=0)

**Comment by deinca** [comment]
Oke @MartijnKeesmaat I'll check it out if I can fix it :D

**Comment by deinca** [comment]
Hey @MartijnKeesmaat this how registration dropdown-menu en radio looks right now. I already push my branch. I guess I have to let him review, right ?
![Schermafbeelding 2019-04-11 om 18 39 30](https://user-images.githubusercontent.com/44967374/55975257-e132f980-5c89-11e9-8088-44e5872536ff.png)

**Comment by Loquino** [comment]
Hey @MartijnKeesmaat this how registration dropdown-menu en radio looks right now. I already push my branch. I guess I have to let him review, right ?
