### ISSUE TITLE
Register page is broken

### ISSUE THREAD

**Issue by MartijnKeesmaat** [MartijnKeesmaat/Dating-app-pt#25]
There is a bug when you create an account. This worked before, but since the implementation of the greeting on the home screen via sessions, it broke. I think the route for the register post request is missing the login data from the session. 

Don't forget to create a new branch with
- git branch fix/register
- git checkout fix/register

[Screenshot](https://www.dropbox.com/s/4a8x0zcldh9rsnm/Schermafdruk%202019-04-10%2013.20.21.png?dl=0)

**Comment by victorlaforga** [comment]
fixed bug
